export interface ReviewEntry {
  text: string;
  reviewer: string;
}

export interface AffiliateEntry {
  id: number;
  name: string;
  tp_title: string;
  tp_url: string;
  website: string;
  reviews: number | null;
  rating: number | null;
  geo: string[];
  affiliate: string;
  owner: string;
  description: string;
  countries_of_reviewers: string[];
  reviews_text: ReviewEntry[];
  warning?: boolean;
}

export const GEO_FILTERS = ['All', 'AU', 'DE', 'CA', 'DK', 'IT'] as const;

export const SORT_OPTIONS = [
  { value: 'reviews_desc', label: 'Sort: Most Reviews' },
  { value: 'reviews_asc', label: 'Sort: Fewest Reviews' },
  { value: 'alpha', label: 'Sort: A\u2013Z' },
  { value: 'geo', label: 'Sort: By Geo' },
] as const;

export const COUNTRY_META: Record<string, { flag: string; name: string }> = {
  AU: { flag: '\u{1F1E6}\u{1F1FA}', name: 'Australia' },
  DE: { flag: '\u{1F1E9}\u{1F1EA}', name: 'Germany' },
  CA: { flag: '\u{1F1E8}\u{1F1E6}', name: 'Canada' },
  DK: { flag: '\u{1F1E9}\u{1F1F0}', name: 'Denmark' },
  IT: { flag: '\u{1F1EE}\u{1F1F9}', name: 'Italy' },
  Multiple: { flag: '\u{1F30D}', name: 'Multi-Region' },
};

export const AFFILIATE_DATA: AffiliateEntry[] = [
  {
    id: 1,
    name: 'SuppliesToBuy',
    tp_title: 'SuppliesToBuy',
    tp_url: 'au.trustpilot.com/review/suppliestobuy.com',
    website: 'suppliestobuy.com',
    reviews: 136,
    rating: 4.5,
    geo: ['AU'],
    affiliate: 'Liberty LTD',
    owner: 'Supriya Kumari',
    description: 'Online tool retailer providing Aussies with best pricing on power tools.',
    countries_of_reviewers: ['AU'],
    reviews_text: [
      { text: "First delivery didn't arrive but contacted Dylan and he went out of his way to fix the problem. Excellent customer service, nothing was a problem, very happy with the product and will buy from them again. Thanks Dylan.", reviewer: 'Terry \u00b7 AU' },
      { text: 'Bought a Makita Duel Port Charger and 2x 5.0AH batteries. The purchase price was the cheapest I could find anywhere. Supplies to Buy is completely honest and totally reliable. My package of genuine Makita components arrived undamaged and very quickly. The ability to pay with PayPal is a deal clincher. Totally Recommend.', reviewer: 'Bruce Wallis \u00b7 AU' },
      { text: 'Was cautious because new retailer, and (almost suspiciously) cheap price. But after an exchange of emails with Dylan, was reassured, and everything went super smooth. Very happy with Makita 18V Brushless product.', reviewer: 'Customer \u00b7 AU' },
      { text: "Dylan was very helpful when my items hadn't arrived \u2014 he took no hesitation in gathering up the same goods and express posting them for next day delivery. I like his service so much I just made my second large purchase with him.", reviewer: 'Customer \u00b7 AU' },
      { text: 'I called up about buying a replacement variable speed angle grinder. Dylan saved me over $400 by replacing the brushes in my grinder \u2014 works as good as new. He cares about his customers and isn\'t just in it to make money.', reviewer: 'Customer \u00b7 AU' },
      { text: 'Suppliestobuy had the most competitive pricing I could find, Dylan was prompt in answering my questions honestly. Goods arrived in good time, well-packed. Highly recommended!', reviewer: 'Customer \u00b7 AU' },
    ],
  },
  {
    id: 2,
    name: 'Casino Schnelle Auszahlung',
    tp_title: 'Online Casino mit schneller Auszahlung 2026',
    tp_url: 'de.trustpilot.com/review/casino-schnelle-auszahlung.net',
    website: 'casino-schnelle-auszahlung.net',
    reviews: 7,
    rating: 4.0,
    geo: ['DE', 'Multiple'],
    affiliate: 'DenEva',
    owner: 'Charisse Bartoli',
    description: 'German-language online casino review/comparison site focused on fast withdrawal casinos.',
    countries_of_reviewers: ['DE'],
    reviews_text: [
      { text: 'Ein casino mit schneller auszahlung war mir wichtiger als Bonus. Erste Abhebung 250\u20ac, nach ca. 6 Stunden da. Reicht mir.', reviewer: 'Customer \u00b7 DE' },
      { text: 'Hab nach online casino schnelle auszahlung gesucht, weil ich keinen Bock mehr auf 3-Tage-Wartezeit hatte. Hier gefunden was ich brauchte.', reviewer: 'Customer \u00b7 DE' },
    ],
  },
  {
    id: 3,
    name: 'AussiePokies.net',
    tp_title: 'Best Online Pokies in Australia 2026 | Real Pokies List',
    tp_url: 'au.trustpilot.com/review/aussiepokies.net',
    website: 'aussiepokies.net',
    reviews: 41,
    rating: 4.5,
    geo: ['AU', 'Multiple'],
    affiliate: 'DenBen',
    owner: 'Charisse Bartoli',
    description: 'Best online pokies guide and review site for Australian players.',
    countries_of_reviewers: ['AU'],
    reviews_text: [
      { text: 'SUREWIN The win rate is more than likely, few bugs and low to zero chance of running your deposit all the way down. Good gameplay in terms of the performance overall little framedrops.', reviewer: 'Sam \u00b7 AU' },
      { text: 'Been playing online pokies for a while and honestly this was one of the better experiences. The recommendations helped me find solid sites.', reviewer: 'Customer \u00b7 AU' },
      { text: 'I was initially skeptical about websites that recommend online pokies, especially when you have to click a link first. After checking this platform more, I was pleasantly surprised. They offer high-quality reviews with great info.', reviewer: 'Customer \u00b7 AU' },
      { text: 'Online pokies for real money at this site is ok, some pokies load slow on mobile. Bonuses work, had to check T&C twice, but cashout came through in 1 day.', reviewer: 'Victoria Johnson \u00b7 AU' },
    ],
  },
  {
    id: 4,
    name: 'PokiesAustralia.site',
    tp_title: 'Online Pokies Australia 2026',
    tp_url: 'au.trustpilot.com/review/pokiesaustralia.site',
    website: 'pokiesaustralia.site',
    reviews: 6,
    rating: 3.9,
    geo: ['AU', 'Multiple'],
    affiliate: 'prstseoteam',
    owner: 'Charisse Bartoli',
    description: 'Online pokies real money Australia review and casino guide site.',
    countries_of_reviewers: ['BR', 'GB', 'DE', 'US'],
    reviews_text: [
      { text: 'nice i love this website to make money, to make withdraw is very fast to receive. Easy verification KYC very fast to be approved. The bonus is very good too.', reviewer: 'Robson Pitoque \u00b7 BR' },
      { text: 'They blocked my account after winning and asked for too many unnecessary documents.', reviewer: 'Md Nibir \u00b7 DE' },
    ],
  },
  {
    id: 5,
    name: 'InstantPayoutCasinos.org',
    tp_title: 'Fastest Withdrawal Online Casinos 2026',
    tp_url: 'au.trustpilot.com/review/instantpayoutcasinos.org',
    website: 'instantpayoutcasinos.org',
    reviews: 17,
    rating: 4.5,
    geo: ['AU', 'Multiple'],
    affiliate: 'DenBen',
    owner: 'Charisse Bartoli',
    description: 'Guide to fastest withdrawal online casinos in Australia \u2014 instant payout casino reviews.',
    countries_of_reviewers: ['AU'],
    reviews_text: [
      { text: "I'm genuinely impressed by how quickly the payouts were processed. With other online casinos that advertise instant withdrawals, I've had to wait days \u2014 but this time the money was in my account within just a few hours. Customer support responded promptly and was very helpful.", reviewer: 'Jaxon Chubb \u00b7 AU' },
      { text: 'If quick access to real winnings is important to you, fast withdrawal casinos are the smartest choice. This site highlights operators that have proven payout times.', reviewer: 'Customer \u00b7 AU' },
    ],
  },
  {
    id: 6,
    name: 'Top 10 Deutsche Online Casinos',
    tp_title: 'Deutsche Online Casinos 2025 | Bestes Online Casino',
    tp_url: 'de.trustpilot.com/review/top10-deutsche-online-casinos.net',
    website: 'top10-deutsche-online-casinos.net',
    reviews: 5,
    rating: 4.1,
    geo: ['DE', 'Multiple'],
    affiliate: 'DenBen',
    owner: 'Charisse Bartoli',
    description: 'German online casino top-10 comparison site \u2014 licensed DE operators only.',
    countries_of_reviewers: ['DE'],
    reviews_text: [
      { text: 'Nutze Vergleichsseiten seit Jahren und schaue mir oft neue deutsche online casinos an. Diese Seite wirkt angenehm sachlich. Statt leerer Versprechen werden RTP, Auszahlungszeiten und Technik verglichen.', reviewer: 'Customer \u00b7 DE' },
      { text: 'Hab die Seite genutzt, um legale deutsche online casinos zu finden. \u00dcbersichtlich aufgebaut, klare Infos zu Limits und Zahlungen. Solide Hilfe ohne Marketing-Blabla.', reviewer: 'Customer \u00b7 DE' },
      { text: 'Spiele schon l\u00e4nger in deutschen online casinos und suche immer wieder nach dem besten. Hier wird transparent erkl\u00e4rt warum bestimmte Regeln und Limits existieren.', reviewer: 'Customer \u00b7 DE' },
    ],
  },
  {
    id: 7,
    name: 'No Deposit Free Spins',
    tp_title: 'Free Spins No Deposit | Best Free Spins Casinos',
    tp_url: 'au.trustpilot.com/review/no-deposit-free-spins.net',
    website: 'no-deposit-free-spins.net',
    reviews: 3,
    rating: 3.7,
    geo: ['AU', 'Multiple'],
    affiliate: 'DenBen',
    owner: 'Charisse Bartoli',
    description: 'Free spins no deposit casino list for Australian players and global markets.',
    countries_of_reviewers: ['AU'],
    reviews_text: [
      { text: 'They actually list casinos that give free spins on popular slots. Saw spins for Big Bass Bonanza, Sweet Bonanza, Gates of Olympus. Wagering looks reasonable. Solid list overall.', reviewer: 'Customer \u00b7 AU' },
      { text: 'Nice to see free spins casino options focused on Australia. Saw offers like 100 free spins no deposit Australia, good enough to test the slot before committing.', reviewer: 'Customer \u00b7 AU' },
      { text: 'Was just looking for no deposit free spins. Found a couple of decent options, nothing crazy but usable.', reviewer: 'Customer \u00b7 AU' },
    ],
  },
  {
    id: 8,
    name: 'Paysafecard Casinos',
    tp_title: 'Paysafecard Casino - Die besten Online-Casinos mit Paysafe',
    tp_url: 'de.trustpilot.com/review/paysafecardcasinos.org',
    website: 'paysafecardcasinos.org',
    reviews: 6,
    rating: 3.7,
    geo: ['DE', 'Multiple'],
    affiliate: 'DenBen',
    owner: 'Charisse Bartoli',
    description: 'German/Austrian guide to online casinos accepting Paysafecard payments.',
    countries_of_reviewers: ['DE', 'AT'],
    reviews_text: [
      { text: 'Fand gut dass es online casino paysafecard 10\u20ac gibt. Wollte erst klein starten. Einzahlung ging durch, slots ganz normal.', reviewer: 'Angelika \u00b7 DE' },
      { text: 'Ich nutze paysafecard schon lange und hatte keine Lust mehr alles selbst zusammenzusuchen. Hier bin ich auf eine \u00dcbersicht gesto\u00dfen \u2014 hat mir echt geholfen. Hab ein online casino mit paysafe ausgew\u00e4hlt, ohne kreditkarte, ohne nervige Schritte.', reviewer: 'Customer \u00b7 DE' },
      { text: 'Ist ok. Hab ein casino paysafecard ohne oasis gesucht und hier ein paar Optionen gefunden.', reviewer: 'Customer \u00b7 DE' },
    ],
  },
  {
    id: 9,
    name: 'Real Money Online Casinos (CA)',
    tp_title: 'Best Online Casinos 2026 \u2b50\ufe0f Canadian Top Casinos',
    tp_url: 'ca.trustpilot.com/review/real-money-online-casinos.net',
    website: 'real-money-online-casinos.net',
    reviews: 6,
    rating: 4.0,
    geo: ['CA', 'Multiple'],
    affiliate: 'DenBen',
    owner: 'Charisse Bartoli',
    description: 'Best online casinos 2026 for Canadian players \u2014 licensed, fast payouts, CAD support.',
    countries_of_reviewers: ['CA'],
    reviews_text: [
      { text: 'Canadian players have access to a wide selection of trusted online casino sites offering thousands of slot machines, immersive live dealer tables, and classic card games.', reviewer: 'Customer \u00b7 CA' },
    ],
  },
  {
    id: 10,
    name: 'Top Aussie Online Casinos',
    tp_title: 'Australian Online Casinos \u2013 Best Real Money Casinos 2026',
    tp_url: 'au.trustpilot.com/review/topaussieonlinecasinos.net',
    website: 'topaussieonlinecasinos.net',
    reviews: 11,
    rating: 4.2,
    geo: ['AU', 'Multiple'],
    affiliate: 'DenBen',
    owner: 'Charisse Bartoli',
    description: 'Australian online casino comparison \u2014 real money, bonuses, payment methods, fast withdrawals.',
    countries_of_reviewers: ['AU'],
    reviews_text: [
      { text: 'A big plus is that it honestly lists the downsides of each casino, not just the positives. Really appreciated the balance.', reviewer: 'Customer \u00b7 AU' },
      { text: 'Casino online australia was doing my head in \u2014 too many dodgy sites out there. Picked one from this page, deposited, played, withdrew. No drama, no mucking around.', reviewer: 'Customer \u00b7 AU' },
      { text: 'Best Australian online casino was what I was searching for after getting stuck on a slow withdrawal elsewhere. Found a legit Australian online casino here and finally got paid without chasing support.', reviewer: 'Customer \u00b7 AU' },
    ],
  },
  {
    id: 11,
    name: 'Casino Ohne OASIS',
    tp_title: 'Casino Ohne OASIS \u{1F3C6} Spieltipps f\u00fcr den 2026',
    tp_url: 'trustpilot.com/review/casinoohneoasis.site',
    website: 'casinoohneoasis.site',
    reviews: 114,
    rating: 4.3,
    geo: ['DE', 'Multiple'],
    affiliate: 'prstseoteam / boringseo',
    owner: 'Charisse Bartoli',
    description: 'Guide to German online casinos without OASIS self-exclusion system \u2014 comprehensive reviews.',
    countries_of_reviewers: ['DE', 'Multiple'],
    reviews_text: [
      { text: 'Lanista (without OASIS) is a great casino. Simple registration, smooth games, and fast payouts. Perfect for gamblers looking to win. I recommend it.', reviewer: 'Customer \u00b7 DE' },
      { text: 'I mostly play on my phone while commuting, and the mobile version of this site is really responsive. Everything is easy to find, and the games load without any lag.', reviewer: 'Customer \u00b7 DE' },
      { text: "Honestly, it's such a relief to find a site that actually lets you play at your own pace. I was getting so tired of those forced 5-second pauses and tiny betting limits on local sites.", reviewer: 'Customer \u00b7 DE' },
      { text: 'I found this site while looking for clear information about casinos without OASIS, and it turned out to be very helpful. The explanations are easy to understand.', reviewer: 'Customer \u00b7 DE' },
      { text: 'Just had an incredible winning session at Casino Ohne Oasis! The games, especially their live dealer section, are top-tier and feel incredibly fair.', reviewer: 'Customer \u00b7 DE' },
    ],
  },
  {
    id: 12,
    name: 'BestCasinos-Aus.com',
    tp_title: 'Top 10 Australian Online Casinos',
    tp_url: 'trustpilot.com/review/bestcasinos-aus.com',
    website: 'bestcasinos-aus.com',
    reviews: 18,
    rating: 4.1,
    geo: ['AU', 'Multiple'],
    affiliate: 'boringseo',
    owner: 'Charisse Bartoli',
    description: 'Top 10 Australian online casino reviews \u2014 independent resource with honest rankings.',
    countries_of_reviewers: ['AU'],
    reviews_text: [
      { text: "I've been going through different sites but the top 10 online Australian casinos featured here are legit. I tried out some of the pokies mentioned in their reviews and actually hit a decent jackpot last night.", reviewer: 'Customer \u00b7 AU' },
      { text: "Found what I needed regarding the best online casino in Australia here. The reviews are quite detailed and helped me avoid a couple of shady sites. Only downside is the web design.", reviewer: 'Customer \u00b7 AU' },
    ],
  },
  {
    id: 13,
    name: '100 Casino Bonus',
    tp_title: '100 % casino bonus',
    tp_url: 'trustpilot.com/review/100casinobonus.info',
    website: '100casinobonus.info',
    reviews: 17,
    rating: 4.3,
    geo: ['Multiple'],
    affiliate: 'Slimsumo',
    owner: 'Gemma',
    description: 'Best 100% casino bonus offers \u2014 verified no-deposit deals, free spins, fast payouts.',
    countries_of_reviewers: ['Multiple'],
    reviews_text: [
      { text: 'I received free spins in addition to a 100% welcome bonus. Played table games and slots without issues.', reviewer: 'Customer' },
      { text: 'A location with actual, functional advantages at last. Without any delay, my 100% matching bonus was credited.', reviewer: 'Customer' },
      { text: 'Nice to see no deposit bonuses listed alongside the big 100% match deals. Good value.', reviewer: 'Customer' },
      { text: 'Bonus was credited without needing support. Clear rules and fair limits.', reviewer: 'Customer' },
      { text: 'Good overview of trusted casino offers. I used a bonus with free spins and fast payout.', reviewer: 'Customer' },
    ],
  },
  {
    id: 14,
    name: 'Top 10 Online Casinos Canada',
    tp_title: 'Top 10 Online Casinos Canada',
    tp_url: 'ca.trustpilot.com/review/top-10-online-casinos-canada.site',
    website: 'top-10-online-casinos-canada.site',
    reviews: 4,
    rating: 4.0,
    geo: ['CA'],
    affiliate: 'Slimsumo',
    owner: 'Gemma',
    description: 'Top 10 online casinos guide for Canadian players.',
    countries_of_reviewers: ['CA'],
    reviews_text: [
      { text: 'Four reviews on record. Focused on top casino ranking for Canadian players.', reviewer: 'Various \u00b7 CA' },
    ],
  },
  {
    id: 15,
    name: 'Casino Online Esteri',
    tp_title: 'Migliori Casino Online Esteri',
    tp_url: 'it.trustpilot.com/review/casino-online-esteri.com',
    website: 'casino-online-esteri.com',
    reviews: 3,
    rating: 4.0,
    geo: ['IT'],
    affiliate: 'Matching Visions Ltd',
    owner: 'Gemma',
    description: 'Italian guide to foreign/international online casinos \u2014 verified, licensed operators.',
    countries_of_reviewers: ['IT'],
    reviews_text: [
      { text: "Mi piace il fatto che il sito selezioni solo casin\u00f2 verificati e con licenze valide. Ho usufruito di un bonus senza deposito e ho potuto provare vari giochi senza rischiare troppo. Lo consiglio a chi cerca un'esperienza trasparente e sicura.", reviewer: 'Customer \u00b7 IT' },
      { text: 'Questo sito \u00e8 perfetto per chi cerca casin\u00f2 esteri affidabili e moderni. Tutte le informazioni sono chiare, aggiornate e spiegate bene. Ho provato due siti consigliati e sono rimasto colpito dalla velocit\u00e0 dei pagamenti.', reviewer: 'Customer \u00b7 IT' },
      { text: 'Ho scoperto alcuni nuovi casin\u00f2 stranieri tramite questo sito e mi sono trovato benissimo. Iscrizione veloce e modalit\u00e0 di pagamento come PayPal e carta accettate senza problemi. Bonus e giri gratis molto generosi.', reviewer: 'Enzo \u00b7 IT' },
    ],
  },
  {
    id: 16,
    name: 'Neue Wettanbieter',
    tp_title: 'Neue Wettanbieter',
    tp_url: 'de.trustpilot.com/review/neuewettanbieter.pro',
    website: 'neuewettanbieter.pro',
    reviews: null,
    rating: null,
    geo: ['DE'],
    affiliate: 'Matching Visions Ltd',
    owner: 'Gemma',
    description: 'German new betting providers comparison and review site.',
    countries_of_reviewers: ['DE'],
    reviews_text: [
      { text: 'No public review data retrieved. Page may be newly launched.', reviewer: '\u2014' },
    ],
  },
  {
    id: 17,
    name: 'Grimme Aelling (Casino uden Rofus)',
    tp_title: 'Casino uden Rofus',
    tp_url: 'dk.trustpilot.com/review/www.grimme-aelling.dk',
    website: 'grimme-aelling.dk',
    reviews: 5,
    rating: 3.85,
    geo: ['DK'],
    affiliate: 'K2 Affiliates',
    owner: 'Charisse Bartoli',
    description: 'Danish casino guide \u2014 casinos without ROFUS self-exclusion.',
    countries_of_reviewers: ['DK'],
    reviews_text: [
      { text: '5 reviews recorded on the Danish Trustpilot page. Casino uden Rofus niche site for Denmark.', reviewer: 'Various \u00b7 DK' },
    ],
  },
  {
    id: 18,
    name: 'Casino Ohne OASIS (DE subdomain)',
    tp_title: 'Casino Ohne OASIS \u{1F3C6} Spieltipps f\u00fcr den 2026',
    tp_url: 'de.trustpilot.com/review/casinoohneoasis.site',
    website: 'casinoohneoasis.site',
    reviews: 114,
    rating: 4.3,
    geo: ['DE', 'Multiple'],
    affiliate: 'boringseo',
    owner: 'Charisse Bartoli',
    description: 'Same casinoohneoasis.site \u2014 German subdomain of Trustpilot listing (mirrors main page).',
    countries_of_reviewers: ['DE', 'Multiple'],
    reviews_text: [
      { text: "I wasn't really expecting much, but I decided to play a bit one evening. The site didn't feel cluttered, the games ran smoothly, and I didn't have to dig around to understand what the offers meant.", reviewer: 'Customer \u00b7 DE' },
    ],
  },
  {
    id: 19,
    name: 'Trustpillot Casino (ohne-oasis)',
    tp_title: '\u26a0\ufe0f Fake/Typo Domain \u2014 Not Trustpilot',
    tp_url: 'trustpillot-casino.com/ohne-oasis',
    website: 'trustpillot-casino.com',
    reviews: null,
    rating: null,
    geo: ['DE', 'Multiple'],
    affiliate: 'boringseo',
    owner: 'Charisse Bartoli',
    description: '\u26a0\ufe0f NOT a real Trustpilot page. This is a typo-domain (trustpillot) masquerading as Trustpilot for casino traffic.',
    countries_of_reviewers: [],
    reviews_text: [
      { text: "\u26a0\ufe0f Warning: This URL points to trustpillot-casino.com (note double 'l') \u2014 a fake/typo domain, NOT trustpilot.com. No legitimate review data available.", reviewer: '\u2014' },
    ],
    warning: true,
  },
  {
    id: 20,
    name: 'Trustpillot Casino (no)',
    tp_title: '\u26a0\ufe0f Fake/Typo Domain \u2014 Not Trustpilot',
    tp_url: 'trustpillot-casino.com/no',
    website: 'trustpillot-casino.com',
    reviews: null,
    rating: null,
    geo: ['Multiple'],
    affiliate: 'boringseo',
    owner: 'Charisse Bartoli',
    description: '\u26a0\ufe0f NOT a real Trustpilot page. Same typo-domain as above, different path.',
    countries_of_reviewers: [],
    reviews_text: [
      { text: "\u26a0\ufe0f Warning: This URL points to trustpillot-casino.com (note double 'l') \u2014 a fake/typo domain, NOT trustpilot.com. No legitimate review data available.", reviewer: '\u2014' },
    ],
    warning: true,
  },
  {
    id: 21,
    name: 'PayID Casino',
    tp_title: 'PayID Pokies Sites 2026 (full pokies list available below)',
    tp_url: 'au.trustpilot.com/review/payid-casino.net',
    website: 'payid-casino.net',
    reviews: 21,
    rating: 4.4,
    geo: ['AU'],
    affiliate: 'GGG',
    owner: 'Charisse Bartoli',
    description: 'PayID pokies sites guide for Australian casino players \u2014 instant withdrawal focus.',
    countries_of_reviewers: ['AU'],
    reviews_text: [
      { text: "Honestly, I didn't expect it to be this smooth. I signed up for one of the online casinos with PayID and had my first win the same night \u2014 the payout hit my bank in under an hour.", reviewer: 'Customer \u00b7 AU' },
      { text: 'Way better than spending hours googling online pokies with PayID and hoping for the best. This site filters out the rubbish and only shows options that actually work!', reviewer: 'Customer \u00b7 AU' },
      { text: 'This site actually seems to vet the PayID pokies they recommend instead of just listing every casino out there. Saved me from wasting deposits on places with sketchy withdrawal rules.', reviewer: 'Customer \u00b7 AU' },
    ],
  },
  {
    id: 22,
    name: 'Best PayID Pokies',
    tp_title: '\u26a1\ufe0fBest PayID Pokies Sites 2026 | PayID Fast Withdrawals',
    tp_url: 'trustpilot.com/review/bestpayidpokies.net',
    website: 'bestpayidpokies.net',
    reviews: 48,
    rating: 4.5,
    geo: ['AU'],
    affiliate: 'GGG',
    owner: 'Charisse Bartoli',
    description: 'Best PayID pokies sites 2026 \u2014 independent AU reviews, fast withdrawal rankings.',
    countries_of_reviewers: ['AU'],
    reviews_text: [
      { text: "The PayID deposit casino I found here has instant withdrawals and the KYC was a breeze. Can't complain.", reviewer: 'Customer \u00b7 AU' },
      { text: 'Online pokies PayID deposit is decent, but the verification dragged a little \u2014 still, bonuses helped me cashout a good sum eventually.', reviewer: 'Customer \u00b7 AU' },
    ],
  },
  {
    id: 23,
    name: 'Pokies Gambler',
    tp_title: 'Best Online Pokies in Australia 2026',
    tp_url: 'trustpilot.com/review/pokiesgambler.com',
    website: 'pokiesgambler.com',
    reviews: 24,
    rating: 4.5,
    geo: ['AU'],
    affiliate: 'GGG',
    owner: 'Charisse Bartoli',
    description: 'Best online pokies in Australia 2026 \u2014 casino reviews with honest pros and cons.',
    countries_of_reviewers: ['AU'],
    reviews_text: [
      { text: 'Solid resource for finding new pokies to try. Would be 5 stars if they added more videos of the actual gameplay.', reviewer: 'Customer \u00b7 AU' },
      { text: "My fav site right now, still took off a star because their reviews don't really explain how often bonuses trigger \u2014 which would be helpful.", reviewer: 'Customer \u00b7 AU' },
      { text: "Decent site for Aussie pokie players. Their recommendations are good and I've had no dramas with any of them. Reviews could go into more detail about max wins but overall does the job well enough.", reviewer: 'Customer \u00b7 AU' },
    ],
  },
  {
    id: 24,
    name: 'Udenlandske Casinoer Uden ROFUS',
    tp_title: 'Udenlandske Casinoer Uden Rofus',
    tp_url: 'trustpilot.com/review/udenlandske-casinoer-uden-rofus.com',
    website: 'udenlandske-casinoer-uden-rofus.com',
    reviews: 2,
    rating: 4.0,
    geo: ['DK'],
    affiliate: 'Slimsumo',
    owner: 'Gemma',
    description: 'Danish guide to foreign casinos without ROFUS \u2014 anonymous play, fast payouts.',
    countries_of_reviewers: ['DK'],
    reviews_text: [
      { text: "Hvis man vil i gang uden at drukne i information, er denne side et godt sted at starte. (Translation: If you want to get started without drowning in information, this is a good place to start.)", reviewer: 'Customer \u00b7 DK' },
    ],
  },
  {
    id: 25,
    name: 'Top 10 Online Casino Australia',
    tp_title: 'Top 10 Online Casino Australia Real Money - Fast Withdrawals',
    tp_url: 'au.trustpilot.com/review/top-10-online-casino-australia.com',
    website: 'top-10-online-casino-australia.com',
    reviews: 15,
    rating: 4.3,
    geo: ['AU'],
    affiliate: 'Slimsumo',
    owner: 'Gemma',
    description: 'Top 10 online casino Australia real money \u2014 fast withdrawals, PayID, AUD-friendly.',
    countries_of_reviewers: ['AU'],
    reviews_text: [
      { text: 'This platform helped me find a couple of new casinos that actually pay out quickly. I appreciated the clear breakdown of payment methods, especially for Aussies using bank transfers or e-wallets.', reviewer: 'Customer \u00b7 AU' },
      { text: "Instead of browsing endless sites, I had everything summarised in one spot. I quickly found one with PayPal deposits and fair wagering. Saved me a lot of time and frustration.", reviewer: 'Dzenita Halilovic \u00b7 AU' },
      { text: "I liked how the site focuses only on casinos that actually accept Australian players. The filtering options made it easy to compare bonuses and games.", reviewer: 'Kath Jackson \u00b7 AU' },
    ],
  },
];
